const money = (value) => `₹${Number(value || 0).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

function escapeHtml(value) {
  return String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
}

export function invoiceHtml(invoice) {
  const customer = invoice.customer || {};
  const vehicle = invoice.vehicle || {};
  const booking = invoice.booking || {};
  const service = booking.service || {};
  const rows = (invoice.items || []).map((item) => `
    <tr>
      <td>${escapeHtml(item.name)}<div class="muted">${escapeHtml(item.type || 'service')}</div></td>
      <td class="num">${item.quantity}</td>
      <td class="num">${money(item.price)}</td>
      <td class="num">${money(item.total)}</td>
    </tr>`).join('');

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(invoice.invoiceNumber)}</title>
  <style>
    body { font-family: 'Segoe UI', Arial, sans-serif; color: #102a43; margin: 0; padding: 32px; }
    .sheet { max-width: 760px; margin: 0 auto; }
    .head { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 3px solid #e86f33; padding-bottom: 18px; }
    .brand { font-size: 28px; font-weight: 700; letter-spacing: -0.5px; }
    .brand span { color: #e86f33; }
    .muted { color: #6f8191; font-size: 12px; margin-top: 4px; }
    h1 { margin: 0 0 6px; font-size: 22px; text-align: right; }
    .meta { display: grid; grid-template-columns: 1fr 1fr; gap: 18px; margin: 24px 0; }
    table { width: 100%; border-collapse: collapse; }
    th { text-align: left; font-size: 11px; letter-spacing: 1px; text-transform: uppercase; color: #6f8191; border-bottom: 1px solid #e4eaf0; padding: 8px 6px; }
    td { padding: 12px 6px; border-bottom: 1px solid #eef2f5; font-size: 13px; vertical-align: top; }
    .num { text-align: right; white-space: nowrap; }
    .totals { width: 280px; margin-left: auto; margin-top: 16px; }
    .totals div { display: flex; justify-content: space-between; padding: 6px 0; font-size: 13px; }
    .grand { font-size: 18px; font-weight: 700; border-top: 2px solid #102a43; margin-top: 8px; padding-top: 10px; }
    .status { display: inline-block; padding: 4px 8px; background: #e3f3ee; color: #278463; font-size: 11px; font-weight: 700; text-transform: uppercase; }
    .foot { margin-top: 40px; font-size: 11px; color: #6f8191; }
    @media print { body { padding: 0; } }
  </style>
</head>
<body>
  <div class="sheet">
    <div class="head">
      <div>
        <div class="brand">F<span>/</span> Forge Auto</div>
        <div class="muted">Vehicle Service Management<br/>Workshop invoice</div>
      </div>
      <div>
        <h1>${escapeHtml(invoice.invoiceNumber)}</h1>
        <div class="muted">${new Date(invoice.createdAt).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}</div>
        <div class="status">${escapeHtml(invoice.paymentStatus || 'Pending')}</div>
      </div>
    </div>
    <div class="meta">
      <div>
        <div class="muted">BILLED TO</div>
        <strong>${escapeHtml(customer.name || 'Customer')}</strong>
        <div class="muted">${escapeHtml(customer.email || '')}${customer.phone ? `<br/>${escapeHtml(customer.phone)}` : ''}${customer.address ? `<br/>${escapeHtml(customer.address)}` : ''}</div>
      </div>
      <div>
        <div class="muted">VEHICLE & SERVICE</div>
        <strong>${escapeHtml([vehicle.brand, vehicle.model].filter(Boolean).join(' ') || 'Vehicle')}</strong>
        <div class="muted">${escapeHtml(vehicle.registrationNumber || '')}${service.name ? `<br/>Booked service: ${escapeHtml(service.name)}` : ''}</div>
      </div>
    </div>
    <table>
      <thead><tr><th>Item</th><th class="num">Qty</th><th class="num">Rate</th><th class="num">Amount</th></tr></thead>
      <tbody>${rows}</tbody>
    </table>
    <div class="totals">
      <div><span>Subtotal</span><span>${money(invoice.subtotal)}</span></div>
      <div><span>Discount</span><span>- ${money(invoice.discount)}</span></div>
      <div><span>Tax</span><span>${money(invoice.tax)}</span></div>
      <div class="grand"><span>Total due</span><span>${money(invoice.grandTotal)}</span></div>
    </div>
    ${invoice.notes ? `<p class="muted" style="margin-top:24px"><strong>Notes:</strong> ${escapeHtml(invoice.notes)}</p>` : ''}
    <p class="foot">Generated by Forge Auto · Thank you for your business. Save this page as PDF from the print dialog.</p>
  </div>
</body>
</html>`;
}

export function downloadInvoicePdf(invoice) {
  const html = invoiceHtml(invoice);
  const frame = document.createElement('iframe');
  frame.setAttribute('aria-hidden', 'true');
  frame.style.cssText = 'position:fixed;right:0;bottom:0;width:0;height:0;border:0;';
  document.body.appendChild(frame);
  const doc = frame.contentDocument;
  doc.open();
  doc.write(html);
  doc.close();
  const trigger = () => {
    frame.contentWindow.focus();
    frame.contentWindow.print();
    setTimeout(() => frame.remove(), 1500);
  };
  if (frame.contentDocument.readyState === 'complete') trigger();
  else frame.onload = trigger;
}
